In [7]:
import pandas as pd
import statsmodels.formula.api as smf
import os
import numpy as np

code pour lundi. manque landlocked dans le fichier matrix, et pq _x et _y ? fichier matrix à vérifier ou refaire, c'est la base de la suite du projet.

In [27]:
df_main = pd.read_csv("/Users/romain/Desktop/Projets DS/ProjetStat/data_final/FINAL_GRAVITY_TRAINING_MATRIX.csv")
#print(gravity_data.head())
df_main.columns

Index(['iso3_o', 'iso3_d', 'year', 'migrantCount', 'distcap', 'contig',
       'comlang_off', 'col_dep_ever', 'pop_o', 'pop_15_64_pct_x',
       'pop_65_plus_pct_x', 'IMR_o', 'urban_o', 'LA_o', 'PSR_o', 'pop_d',
       'pop_15_64_pct_y', 'pop_65_plus_pct_y', 'IMR_d', 'urban_d', 'LA_d',
       'PSR_d', 'log_migrantCount', 'log_distcap', 'log_pop_o', 'log_pop_d',
       'log_PSR_o', 'log_PSR_d', 'log_IMR_o', 'log_IMR_d', 'log_urban_o',
       'log_urban_d', 'log_LA_o', 'log_LA_d', 't_centered', 't_centered_sq'],
      dtype='object')

In [28]:
df_main.head(50)

,iso3_o,iso3_d,year,migrantCount,distcap,contig,comlang_off,col_dep_ever,pop_o,pop_15_64_pct_x,...,log_PSR_o,log_PSR_d,log_IMR_o,log_IMR_d,log_urban_o,log_urban_d,log_LA_o,log_LA_d,t_centered,t_centered_sq
0,ABW,AGO,2005,1,9516.913,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,2.940910,2.990720,4.547541,3.803881,4.025352,5.192957,14.036011,5,25
1,ABW,ARE,2005,1,12735.010,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,3.817825,2.990720,2.041220,3.803881,4.409909,5.192957,11.170717,5,25
2,ABW,ARE,2010,1,12735.010,0.0,0.0,0.0,101838.0,69.709380,...,1.994177,4.051080,2.890372,1.945910,3.762571,4.431852,5.192957,11.170717,10,100
3,ABW,ARG,1995,1,5396.220,0.0,1.0,0.0,79805.0,67.362813,...,2.372545,1.894259,3.081910,3.039749,3.887054,4.479199,5.192957,14.822260,-5,25
4,ABW,ARG,2000,1,5396.220,0.0,1.0,0.0,90588.0,69.774621,...,2.331547,1.861960,3.058707,2.815409,3.844108,4.490231,5.192957,14.822260,0,0
5,ABW,ARG,2005,1,5396.220,0.0,1.0,0.0,97635.0,70.108246,...,2.154336,1.845557,2.990720,2.667228,3.803881,4.500154,5.192957,14.822260,5,25
6,ABW,ARG,2010,1,5396.220,0.0,1.0,0.0,101838.0,69.709380,...,1.994177,1.815582,2.890372,2.517696,3.762571,4.509199,5.192957,14.822260,10,100
7,ABW,ATG,1990,1,1024.995,0.0,0.0,0.0,62753.0,67.390157,...,2.234410,1.914993,3.104587,2.406945,3.918383,3.567446,5.192957,6.086775,-10,100
8,ABW,ATG,1995,2,1024.995,0.0,0.0,0.0,79805.0,67.362813,...,2.372545,2.053315,3.081910,2.533697,3.887054,3.525213,5.192957,6.086775,-5,25
9,ABW,ATG,2000,1,1024.995,0.0,0.0,0.0,90588.0,69.774621,...,2.331547,2.176426,3.058707,2.501436,3.844108,3.469697,5.192957,6.086775,0,0
10,ABW,ATG,2005,1,1024.995,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,2.243593,2.990720,2.379546,3.803881,3.374785,5.192957,6.086775,5,25
11,ABW,ATG,2010,1,1024.995,0.0,0.0,0.0,101838.0,69.709380,...,1.994177,2.267810,2.890372,2.251292,3.762571,3.267209,5.192957,6.086775,10,100
12,ABW,AUS,1990,2,15354.320,0.0,0.0,0.0,62753.0,67.390157,...,2.234410,1.800043,3.104587,2.028148,3.918383,4.447732,5.192957,15.854430,-10,100
13,ABW,AUS,1995,26,15354.320,0.0,0.0,0.0,79805.0,67.362813,...,2.372545,1.726940,3.081910,1.757858,3.887054,4.441451,5.192957,15.854430,-5,25
14,ABW,AUS,2000,7,15354.320,0.0,0.0,0.0,90588.0,69.774621,...,2.331547,1.690621,3.058707,1.629241,3.844108,4.433611,5.192957,15.854430,0,0
15,ABW,AUS,2005,17,15354.320,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,1.653858,2.990720,1.568616,3.803881,4.437721,5.192957,15.854430,5,25
16,ABW,AUS,2010,10,15354.320,0.0,0.0,0.0,101838.0,69.709380,...,1.994177,1.605816,2.890372,1.386294,3.762571,4.444790,5.192957,15.854430,10,100
17,ABW,AUT,1990,1,8719.130,0.0,0.0,0.0,62753.0,67.390157,...,2.234410,1.507530,3.104587,2.079442,3.918383,4.142500,5.192957,11.320796,-10,100
18,ABW,AUT,1995,2,8719.130,0.0,0.0,0.0,79805.0,67.362813,...,2.372545,1.487260,3.081910,1.740466,3.887054,4.120597,5.192957,11.320796,-5,25
19,ABW,AUT,2005,2,8719.130,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,1.430378,2.990720,1.410987,3.803881,4.074363,5.192957,11.320796,5,25
20,ABW,AUT,2010,1,8719.130,0.0,0.0,0.0,101838.0,69.709380,...,1.994177,1.341162,2.890372,1.280934,3.762571,4.050027,5.192957,11.320796,10,100
21,ABW,BEL,1990,1,7847.070,0.0,1.0,0.0,62753.0,67.390157,...,2.234410,1.500901,3.104587,2.116256,3.918383,4.568268,5.192957,10.318243,-10,100
22,ABW,BEL,1995,2,7847.070,0.0,1.0,0.0,79805.0,67.362813,...,2.372545,1.425373,3.081910,1.856298,3.887054,4.572409,5.192957,10.318243,-5,25
23,ABW,BEL,2000,4,7847.070,0.0,1.0,0.0,90588.0,69.774621,...,2.331547,1.361709,3.058707,1.568616,3.844108,4.576040,5.192957,10.318243,0,0
24,ABW,BEL,2005,6,7847.070,0.0,1.0,0.0,97635.0,70.108246,...,2.154336,1.338186,2.990720,1.410987,3.803881,4.578857,5.192957,10.318243,5,25
25,ABW,BEL,2010,6,7847.070,0.0,1.0,0.0,101838.0,69.709380,...,1.994177,1.348695,2.890372,1.308333,3.762571,4.581400,5.192957,10.318243,10,100
26,ABW,BGR,1995,1,9348.039,0.0,0.0,0.0,79805.0,67.362813,...,2.372545,1.489603,3.081910,2.740840,3.887054,4.216297,5.192957,11.613947,-5,25
27,ABW,BGR,2005,3,9348.039,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,1.381154,2.990720,2.397895,3.803881,4.256803,5.192957,11.595795,5,25
28,ABW,BGR,2010,1,9348.039,0.0,0.0,0.0,101838.0,69.709380,...,1.994177,1.326795,2.890372,2.208274,3.762571,4.280852,5.192957,11.595058,10,100
29,ABW,BHS,2000,1,1588.515,0.0,0.0,0.0,90588.0,69.774621,...,2.331547,2.280763,3.058707,2.617396,3.844108,4.406805,5.192957,9.211340,0,0
30,ABW,BHS,2005,1,1588.515,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,2.128130,2.990720,2.674149,3.803881,4.409374,5.192957,9.211340,5,25
31,ABW,BHS,2010,1,1588.515,0.0,0.0,0.0,101838.0,69.709380,...,1.994177,1.998088,2.890372,2.595255,3.762571,4.411913,5.192957,9.211340,10,100
32,ABW,BOL,1995,2,3560.684,0.0,1.0,0.0,79805.0,67.362813,...,2.372545,2.500113,3.081910,4.318821,3.887054,4.080077,5.192957,13.895522,-5,25
33,ABW,BOL,2000,1,3560.684,0.0,1.0,0.0,90588.0,69.774621,...,2.331547,2.378789,3.058707,4.087656,3.844108,4.123693,5.192957,13.895522,0,0
34,ABW,BOL,2005,2,3560.684,0.0,1.0,0.0,97635.0,70.108246,...,2.154336,2.383715,2.990720,3.822098,3.803881,4.161536,5.192957,13.895522,5,25
35,ABW,BOL,2010,1,3560.684,0.0,1.0,0.0,101838.0,69.709380,...,1.994177,2.400179,2.890372,3.552487,3.762571,4.196149,5.192957,13.895522,10,100
36,ABW,BRA,1990,1,3988.915,0.0,0.0,0.0,62753.0,67.390157,...,2.234410,2.684781,3.104587,3.951244,3.918383,4.303010,5.192957,15.938746,-10,100
37,ABW,BRA,1995,1,3988.915,0.0,0.0,0.0,79805.0,67.362813,...,2.372545,2.603449,3.081910,3.683867,3.887054,4.351696,5.192957,15.938746,-5,25
38,ABW,BRA,2000,1,3988.915,0.0,0.0,0.0,90588.0,69.774621,...,2.331547,2.534239,3.058707,3.370738,3.844108,4.396817,5.192957,15.938746,0,0
39,ABW,BRA,2005,4,3988.915,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,2.452751,2.990720,3.044522,3.803881,4.416839,5.192957,15.938746,5,25
40,ABW,BRA,2010,1,3988.915,0.0,0.0,0.0,101838.0,69.709380,...,1.994177,2.331509,2.890372,2.772589,3.762571,4.434797,5.192957,15.938746,10,100
41,ABW,BRB,1990,1,1139.240,0.0,0.0,0.0,62753.0,67.390157,...,2.234410,1.796676,3.104587,2.785011,3.918383,3.620868,5.192957,6.063785,-10,100
42,ABW,BRB,1995,4,1139.240,0.0,0.0,0.0,79805.0,67.362813,...,2.372545,1.795333,3.081910,2.595255,3.887054,3.571390,5.192957,6.063785,-5,25
43,ABW,BRB,2000,1,1139.240,0.0,0.0,0.0,90588.0,69.774621,...,2.331547,1.780561,3.058707,2.564949,3.844108,3.521259,5.192957,6.063785,0,0
44,ABW,BRB,2005,1,1139.240,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,1.787333,2.990720,2.602690,3.803881,3.491678,5.192957,6.063785,5,25
45,ABW,BRB,2010,1,1139.240,0.0,0.0,0.0,101838.0,69.709380,...,1.994177,1.750226,2.890372,2.541602,3.762571,3.461665,5.192957,6.063785,10,100
46,ABW,CAN,1990,60,3696.783,0.0,0.0,0.0,62753.0,67.390157,...,2.234410,1.800731,3.104587,1.916923,3.918383,4.338362,5.192957,16.008904,-10,100
47,ABW,CAN,1995,137,3696.783,0.0,0.0,0.0,79805.0,67.362813,...,2.372545,1.732547,3.081910,1.757858,3.887054,4.352533,5.192957,16.008904,-5,25
48,ABW,CAN,2000,76,3696.783,0.0,0.0,0.0,90588.0,69.774621,...,2.331547,1.694648,3.058707,1.667707,3.844108,4.375480,5.192957,16.008904,0,0
49,ABW,CAN,2005,114,3696.783,0.0,0.0,0.0,97635.0,70.108246,...,2.154336,1.669136,2.990720,1.648659,3.803881,4.383550,5.192957,16.008904,5,25

In [ ]:

df_geo= pd.read_excel("data/geo_cepii.xls")


# 1. On prépare une version "light" de la table geo
# On ne garde que la clé (iso3) et la variable qu'on veut (landlocked)
geo_subset = df_geo[['iso3', 'landlocked']]

# ---------------------------------------------------------
# ÉTAPE 1 : Ajouter Landlocked pour l'ORIGINE (_o)
# ---------------------------------------------------------
df_main = df_main.merge(geo_subset, left_on='iso3_o', right_on='iso3', how='left')

# La colonne s'ajoute sous le nom 'landlocked', on la renomme tout de suite
df_main = df_main.rename(columns={'landlocked': 'landlocked_o'})

# On supprime la colonne 'iso3' qui vient d'être ajoutée en doublon (celle de la table geo)
df_main = df_main.drop(columns=['iso3'])

# ---------------------------------------------------------
# ÉTAPE 2 : Ajouter Landlocked pour la DESTINATION (_d)
# ---------------------------------------------------------
df_main = df_main.merge(geo_subset, left_on='iso3_d', right_on='iso3', how='left')

# On renomme pour la destination
df_main = df_main.rename(columns={'landlocked': 'landlocked_d'})

# On nettoie encore
df_main = df_main.drop(columns=['iso3'])

# Vérification
print(df_main[['iso3_o', 'landlocked_o', 'iso3_d', 'landlocked_d']].head())

  iso3_o  landlocked_o iso3_d  landlocked_d
0    ABW           0.0    AGO           0.0
1    ABW           0.0    ARE           0.0
2    ABW           0.0    ARE           0.0
3    ABW           0.0    ARG           0.0
4    ABW           0.0    ARG           0.0

In [12]:
df_main.head(50)
df_main.columns

Index(['iso3_o', 'iso3_d', 'year', 'migrantCount', 'distcap', 'contig',
       'comlang_off', 'col_dep_ever', 'pop_o', 'pop_15_64_pct_x',
       'pop_65_plus_pct_x', 'IMR_o', 'urban_o', 'LA_o', 'PSR_o', 'pop_d',
       'pop_15_64_pct_y', 'pop_65_plus_pct_y', 'IMR_d', 'urban_d', 'LA_d',
       'PSR_d', 'log_migrantCount', 'log_distcap', 'log_pop_o', 'log_pop_d',
       'log_PSR_o', 'log_PSR_d', 'log_IMR_o', 'log_IMR_d', 'log_urban_o',
       'log_urban_d', 'log_LA_o', 'log_LA_d', 't_centered', 't_centered_sq',
       'landlocked_o', 'landlocked_d'],
      dtype='object')

In [13]:
import statsmodels.formula.api as smf

# 1. Définition de la formule (Variable Y ~ Variables X)
formula = """
log_migrantCount ~ log_pop_o + log_pop_d + log_distcap 
+ log_PSR_o + log_PSR_d + log_IMR_o + log_IMR_d 
+ log_urban_o + log_urban_d + log_LA_o + log_LA_d 
+ landlocked_o + landlocked_d 
+ contig + comlang_off + col_dep_ever 
+ t_centered + t_centered_sq
"""

# 2. Estimation du modèle (On nettoie les NaN avant, sinon ça plante)
# cov_type='HC1' assure des t-stats robustes comme dans votre papier
results = smf.ols(formula, data=df_main.dropna()).fit(cov_type='HC1')

# 3. Affichage
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       log_migrantCount   R-squared:                       0.475
Model:                            OLS   Adj. R-squared:                  0.475
Method:                 Least Squares   F-statistic:                     5625.
Date:                Sun, 18 Jan 2026   Prob (F-statistic):               0.00
Time:                        10:51:47   Log-Likelihood:            -2.2975e+05
No. Observations:              103713   AIC:                         4.595e+05
Df Residuals:                  103694   BIC:                         4.597e+05
Df Model:                          18
Covariance Type:                  HC1
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -1.8191      0.183     -9.955      0.000      -2.177      -1.461
log_pop_o         0.5049      0.006     82.856      0.000       0.493       0.517
log_pop_d         0.4284      0.006     71.445      0.000       0.417       0.440
log_distcap      -1.2205      0.009   -133.205      0.000      -1.238      -1.203
log_PSR_o         0.2119      0.017     12.374      0.000       0.178       0.246
log_PSR_d        -0.1749      0.019     -9.365      0.000      -0.212      -0.138
log_IMR_o        -0.5879      0.012    -47.317      0.000      -0.612      -0.564
log_IMR_d        -0.7422      0.013    -57.743      0.000      -0.767      -0.717
log_urban_o      -0.0491      0.021     -2.392      0.017      -0.089      -0.009
log_urban_d       0.1844      0.021      8.827      0.000       0.143       0.225
log_LA_o          0.1452      0.005     30.163      0.000       0.136       0.155
log_LA_d          0.2099      0.005     43.847      0.000       0.201       0.219
landlocked_o     -0.2756      0.020    -14.125      0.000      -0.314      -0.237
landlocked_d     -0.1012      0.019     -5.459      0.000      -0.138      -0.065
contig            1.9185      0.045     42.560      0.000       1.830       2.007
comlang_off       1.5707      0.019     80.622      0.000       1.533       1.609
col_dep_ever      2.0349      0.045     45.210      0.000       1.947       2.123
t_centered       -0.0429      0.001    -38.815      0.000      -0.045      -0.041
t_centered_sq    -0.0004      0.000     -2.218      0.027      -0.001   -4.26e-05
==============================================================================
Omnibus:                        4.398   Durbin-Watson:                   0.517
Prob(Omnibus):                  0.111   Jarque-Bera (JB):                4.404
Skew:                           0.016   Prob(JB):                        0.111
Kurtosis:                       2.995   Cond. No.                     1.92e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.92e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
df_cepii = pd.read_csv("reg_gravity_CEPII.csv")
df_cepii.head

/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_31438/1892335184.py:1: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  df_cepii = pd.read_csv("reg_gravity_CEPII.csv")

<bound method NDFrame.head of         iso_o  iso_d origIso destIso  year  migrantCount country_id_o  \
0         533      4     ABW     AFG  1990             0          ABW
1         533      4     ABW     AFG  1995             0          ABW
2         533      4     ABW     AFG  2000             0          ABW
3         533      4     ABW     AFG  2005             0          ABW
4         533      4     ABW     AFG  2010             0          ABW
...       ...    ...     ...     ...   ...           ...          ...
198995    716    894     ZWE     ZMB  1990          9676          ZWE
198996    716    894     ZWE     ZMB  1995          4514          ZWE
198997    716    894     ZWE     ZMB  2000         11438          ZWE
198998    716    894     ZWE     ZMB  2005          9939          ZWE
198999    716    894     ZWE     ZMB  2010          9495          ZWE

       country_id_d iso3_o iso3_d  ...  tradeflow_comtrade_o  \
0               AFG    ABW    AFG  ...                   NaN
1               AFG    ABW    AFG  ...                   NaN
2               AFG    ABW    AFG  ...                   NaN
3               AFG    ABW    AFG  ...                   NaN
4               AFG    ABW    AFG  ...                   NaN
...             ...    ...    ...  ...                   ...
198995          ZMB    ZWE    ZMB  ...             51338.780
198996          ZMB    ZWE    ZMB  ...             93024.935
198997          ZMB    ZWE    ZMB  ...             89430.387
198998          ZMB    ZWE    ZMB  ...            103878.714
198999          ZMB    ZWE    ZMB  ...             74231.711

        tradeflow_comtrade_d  tradeflow_baci  manuf_tradeflow_baci  \
0                        NaN             NaN                   NaN
1                        NaN             NaN                   NaN
2                        NaN             NaN                   NaN
3                        NaN             NaN                   NaN
4                        NaN             NaN                   NaN
...                      ...             ...                   ...
198995                   NaN             NaN                   NaN
198996             56481.909             NaN                   NaN
198997              9650.108       89418.449             72656.852
198998            112664.547      114212.344             96854.531
198999             71937.606       78117.156             56695.867

        tradeflow_imf_o  tradeflow_imf_d      LA_o  LL_o      LA_d  LL_d
0                   NaN              NaN     193.0   0.0  652225.0   1.0
1                   NaN              NaN     193.0   0.0  652225.0   1.0
2                   NaN              NaN     193.0   0.0  652225.0   1.0
3                   NaN              NaN     193.0   0.0  652225.0   1.0
4                   NaN              NaN     193.0   0.0  652225.0   1.0
...                 ...              ...       ...   ...       ...   ...
198995        51263.965        56962.555  390759.0   1.0  752614.0   1.0
198996        95414.000        57426.219  390759.0   1.0  752614.0   1.0
198997        78602.289        69420.805  390759.0   1.0  752614.0   1.0
198998        77295.117       110190.109  390759.0   1.0  752614.0   1.0
198999        74231.734        71924.594  390759.0   1.0  752614.0   1.0

[199000 rows x 96 columns]>

In [15]:
df_main.columns

Index(['iso3_o', 'iso3_d', 'year', 'migrantCount', 'distcap', 'contig',
       'comlang_off', 'col_dep_ever', 'pop_o', 'pop_15_64_pct_x',
       'pop_65_plus_pct_x', 'IMR_o', 'urban_o', 'LA_o', 'PSR_o', 'pop_d',
       'pop_15_64_pct_y', 'pop_65_plus_pct_y', 'IMR_d', 'urban_d', 'LA_d',
       'PSR_d', 'log_migrantCount', 'log_distcap', 'log_pop_o', 'log_pop_d',
       'log_PSR_o', 'log_PSR_d', 'log_IMR_o', 'log_IMR_d', 'log_urban_o',
       'log_urban_d', 'log_LA_o', 'log_LA_d', 't_centered', 't_centered_sq',
       'landlocked_o', 'landlocked_d'],
      dtype='object')

In [ ]:
df_cepii.columns

df_cepii_subset = df_cepii[['iso_o']]

Index(['iso_o', 'iso_d', 'origIso', 'destIso', 'year', 'migrantCount',
       'country_id_o', 'country_id_d', 'iso3_o', 'iso3_d', 'iso3num_o',
       'iso3num_d', 'country_exists_o', 'country_exists_d',
       'gmt_offset_2020_o', 'gmt_offset_2020_d', 'distw_harmonic',
       'distw_arithmetic', 'distw_harmonic_jh', 'distw_arithmetic_jh', 'dist',
       'main_city_source_o', 'main_city_source_d', 'distcap', 'contig',
       'diplo_disagreement', 'scaled_sci_2021', 'comlang_off', 'comlang_ethno',
       'comcol', 'col45', 'legal_old_o', 'legal_old_d', 'legal_new_o',
       'legal_new_d', 'comleg_pretrans', 'comleg_posttrans',
       'transition_legalchange', 'comrelig', 'heg_o', 'heg_d', 'col_dep_ever',
       'col_dep', 'col_dep_end_year', 'col_dep_end_conflict', 'empire',
       'sibling_ever', 'sibling', 'sever_year', 'sib_conflict', 'pop_o',
       'pop_d', 'gdp_o', 'gdp_d', 'gdpcap_o', 'gdpcap_d', 'pop_source_o',
       'pop_source_d', 'gdp_source_o', 'gdp_source_d', 'gdp_ppp_o',
       'gdp_ppp_d', 'gdpcap_ppp_o', 'gdpcap_ppp_d', 'pop_pwt_o', 'pop_pwt_d',
       'gdp_ppp_pwt_o', 'gdp_ppp_pwt_d', 'gatt_o', 'gatt_d', 'wto_o', 'wto_d',
       'eu_o', 'eu_d', 'fta_wto', 'fta_wto_raw', 'rta_coverage', 'rta_type',
       'entry_cost_o', 'entry_cost_d', 'entry_proc_o', 'entry_proc_d',
       'entry_time_o', 'entry_time_d', 'entry_tp_o', 'entry_tp_d',
       'tradeflow_comtrade_o', 'tradeflow_comtrade_d', 'tradeflow_baci',
       'manuf_tradeflow_baci', 'tradeflow_imf_o', 'tradeflow_imf_d', 'LA_o',
       'LL_o', 'LA_d', 'LL_d'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np

# 1. Sélection des variables éco utiles
# On prend iso3 + year comme clés
cols_eco = ['iso3_o', 'iso3_d', 'year', 'gdp_o', 'gdp_d', 'gdpcap_o', 'gdpcap_d']
df_eco = df_cepii[cols_eco].copy()



# fusionner valeurs courantes, t 
df_final = df_main.merge(df_eco, on=['iso3_o', 'iso3_d', 'year'], how='left')



# fusionner valeurs retardées, t-5

# Astuce : On crée une colonne 'year_target' = année actuelle + 5 ans.
# L'année 2000 du fichier éco viendra s'accrocher à l'année 2005 du fichier principal.
df_eco_lag = df_eco.copy()
df_eco_lag['year_target'] = df_eco_lag['year'] + 5 

# On renomme les colonnes pour éviter les doublons (suffixe _lag)
cols_lag = {c: f'{c}_lag' for c in ['gdp_o', 'gdp_d', 'gdpcap_o', 'gdpcap_d']}
df_eco_lag = df_eco_lag.rename(columns=cols_lag)

# Fusion sur les clés + la clé temporelle décalée
df_final = df_final.merge(
    df_eco_lag[['iso3_o', 'iso3_d', 'year_target'] + list(cols_lag.values())],
    left_on=['iso3_o', 'iso3_d', 'year'],
    right_on=['iso3_o', 'iso3_d', 'year_target'],
    how='left'
)

# calcul des log (gérer les NaN)
vars_to_log = ['gdp_o', 'gdp_d', 'gdpcap_o', 'gdpcap_d', 
               'gdp_o_lag', 'gdp_d_lag', 'gdpcap_o_lag', 'gdpcap_d_lag']

for col in vars_to_log:
    # On remplace les valeurs <= 0 par NaN pour éviter l'erreur log(0)
    # Statsmodels supprimera automatiquement ces lignes lors de la régression
    df_final[col] = df_final[col].apply(lambda x: x if x > 0 else np.nan)
    df_final[f'log_{col}'] = np.log(df_final[col])

# Nettoyage final
df_final = df_final.drop(columns=['year_target'])

print("Fusion terminée.")
print(df_final[['year', 'log_gdpcap_o', 'log_gdpcap_o_lag']].head())

Fusion terminée.
   year  log_gdpcap_o  log_gdpcap_o_lag
0  2005      3.148582          3.026261
1  2005      3.148582          3.026261
2  2010      3.190024          3.148582
3  1995      2.799778               NaN
4  2000      3.026261          2.799778

In [26]:
df_final.head(50)

,iso3_o,iso3_d,year,migrantCount,distcap,contig,comlang_off,col_dep_ever,pop_o,pop_15_64_pct_x,...,gdpcap_o_lag,gdpcap_d_lag,log_gdp_o,log_gdp_d,log_gdpcap_o,log_gdpcap_d,log_gdp_o_lag,log_gdp_d_lag,log_gdpcap_o_lag,log_gdpcap_d_lag
0,ABW,AGO,2005,1,9516.913,0.0,0.0,0.0,97635.0,70.108246,...,20.620,0.656,14.661810,17.156027,3.148582,0.534737,14.443294,16.027032,3.026261,-0.421594
1,ABW,ARE,2005,1,12735.010,0.0,0.0,0.0,97635.0,70.108246,...,20.620,34.476,14.661810,19.011889,3.148582,3.773542,14.443294,18.463140,3.026261,3.540263
2,ABW,ARE,2010,1,12735.010,0.0,0.0,0.0,101838.0,69.709380,...,23.303,43.534,14.718799,19.471675,3.190024,3.523002,14.661810,19.011889,3.148582,3.773542
3,ABW,ARG,1995,1,5396.220,0.0,1.0,0.0,79805.0,67.362813,...,NaN,4.333,14.093650,19.560336,2.799778,2.194220,NaN,18.766766,NaN,1.466260
4,ABW,ARG,2000,1,5396.220,0.0,1.0,0.0,90588.0,69.774621,...,16.441,8.973,14.443294,19.656945,3.026261,2.233128,14.093650,19.560336,2.799778,2.194220
5,ABW,ARG,2005,1,5396.220,0.0,1.0,0.0,97635.0,70.108246,...,20.620,9.329,14.661810,19.222268,3.148582,1.752325,14.443294,19.656945,3.026261,2.233128
6,ABW,ARG,2010,1,5396.220,0.0,1.0,0.0,101838.0,69.709380,...,23.303,5.768,14.718799,19.952598,3.190024,2.438863,14.661810,19.222268,3.148582,1.752325
7,ABW,ATG,1990,1,1024.995,0.0,0.0,0.0,62753.0,67.390157,...,NaN,NaN,NaN,12.877921,NaN,1.844510,NaN,NaN,NaN,NaN
8,ABW,ATG,1995,2,1024.995,0.0,0.0,0.0,79805.0,67.362813,...,NaN,6.325,14.093650,13.110666,2.799778,1.978239,NaN,12.877921,NaN,1.844510
9,ABW,ATG,2000,1,1024.995,0.0,0.0,0.0,90588.0,69.774621,...,16.441,7.230,14.443294,13.571957,3.026261,2.312040,14.093650,13.110666,2.799778,1.978239
10,ABW,ATG,2005,1,1024.995,0.0,0.0,0.0,97635.0,70.108246,...,20.620,10.095,14.661810,13.812881,3.148582,2.491551,14.443294,13.571957,3.026261,2.312040
11,ABW,ATG,2010,1,1024.995,0.0,0.0,0.0,101838.0,69.709380,...,23.303,12.080,14.718799,13.942618,3.190024,2.566256,14.661810,13.812881,3.148582,2.491551
12,ABW,AUS,1990,2,15354.320,0.0,0.0,0.0,62753.0,67.390157,...,NaN,NaN,NaN,19.555127,NaN,2.902575,NaN,NaN,NaN,NaN
13,ABW,AUS,1990,2,15354.320,0.0,0.0,0.0,62753.0,67.390157,...,NaN,NaN,NaN,19.555127,NaN,2.902575,NaN,NaN,NaN,NaN
14,ABW,AUS,1995,26,15354.320,0.0,0.0,0.0,79805.0,67.362813,...,NaN,18.221,14.093650,19.723655,2.799778,3.013769,NaN,19.555127,NaN,2.902575
15,ABW,AUS,1995,26,15354.320,0.0,0.0,0.0,79805.0,67.362813,...,NaN,18.221,14.093650,19.723655,2.799778,3.013769,NaN,19.555127,NaN,2.902575
16,ABW,AUS,2000,7,15354.320,0.0,0.0,0.0,90588.0,69.774621,...,16.441,20.364,14.443294,19.843758,3.026261,3.075790,14.093650,19.723655,2.799778,3.013769
17,ABW,AUS,2000,7,15354.320,0.0,0.0,0.0,90588.0,69.774621,...,16.441,20.364,14.443294,19.843758,3.026261,3.075790,14.093650,19.723655,2.799778,3.013769
18,ABW,AUS,2005,17,15354.320,0.0,0.0,0.0,97635.0,70.108246,...,20.620,21.667,14.661810,20.357029,3.148582,3.526243,14.443294,19.843758,3.026261,3.075790
19,ABW,AUS,2005,17,15354.320,0.0,0.0,0.0,97635.0,70.108246,...,20.620,21.667,14.661810,20.357029,3.148582,3.526243,14.443294,19.843758,3.026261,3.075790
20,ABW,AUS,2010,10,15354.320,0.0,0.0,0.0,101838.0,69.709380,...,23.303,33.996,14.718799,20.855406,3.190024,3.947409,14.661810,20.357029,3.148582,3.526243
21,ABW,AUS,2010,10,15354.320,0.0,0.0,0.0,101838.0,69.709380,...,23.303,33.996,14.718799,20.855406,3.190024,3.947409,14.661810,20.357029,3.148582,3.526243
22,ABW,AUT,1990,1,8719.130,0.0,0.0,0.0,62753.0,67.390157,...,NaN,NaN,NaN,18.927874,NaN,3.074035,NaN,NaN,NaN,NaN
23,ABW,AUT,1995,2,8719.130,0.0,0.0,0.0,79805.0,67.362813,...,NaN,21.629,14.093650,19.298054,2.799778,3.409595,NaN,18.927874,NaN,3.074035
24,ABW,AUT,2005,2,8719.130,0.0,0.0,0.0,97635.0,70.108246,...,20.620,24.517,14.661810,19.566943,3.148582,3.643908,14.443294,19.095775,3.026261,3.199367
25,ABW,AUT,2010,1,8719.130,0.0,0.0,0.0,101838.0,69.709380,...,23.303,38.241,14.718799,19.780775,3.190024,3.838247,14.661810,19.566943,3.148582,3.643908
26,ABW,BEL,1990,1,7847.070,0.0,1.0,0.0,62753.0,67.390157,...,NaN,NaN,NaN,19.143939,NaN,3.029119,NaN,NaN,NaN,NaN
27,ABW,BEL,1995,2,7847.070,0.0,1.0,0.0,79805.0,67.362813,...,NaN,20.679,14.093650,19.482361,2.799778,3.350676,NaN,19.143939,NaN,3.029119
28,ABW,BEL,2000,4,7847.070,0.0,1.0,0.0,90588.0,69.774621,...,16.441,28.522,14.443294,19.284989,3.026261,3.142081,14.093650,19.482361,2.799778,3.350676
29,ABW,BEL,2005,6,7847.070,0.0,1.0,0.0,97635.0,70.108246,...,20.620,23.152,14.661810,19.773793,3.148582,3.608943,14.443294,19.284989,3.026261,3.142081
30,ABW,BEL,2010,6,7847.070,0.0,1.0,0.0,101838.0,69.709380,...,23.303,36.927,14.718799,19.998430,3.190024,3.792293,14.661810,19.773793,3.148582,3.608943
31,ABW,BGR,1995,1,9348.039,0.0,0.0,0.0,79805.0,67.362813,...,NaN,2.377,14.093650,16.385761,2.799778,0.441476,NaN,16.846914,NaN,0.865839
32,ABW,BGR,2005,3,9348.039,0.0,0.0,0.0,97635.0,70.108246,...,20.620,1.634,14.661810,17.193118,3.148582,1.331310,14.443294,16.407291,3.026261,0.491031
33,ABW,BGR,2010,1,9348.039,0.0,0.0,0.0,101838.0,69.709380,...,23.303,3.786,14.718799,17.700554,3.190024,1.884187,14.661810,17.193118,3.148582,1.331310
34,ABW,BHS,2000,1,1588.515,0.0,0.0,0.0,90588.0,69.774621,...,16.441,12.244,14.443294,15.660424,3.026261,3.056404,14.093650,15.047779,2.799778,2.505036
35,ABW,BHS,2005,1,1588.515,0.0,0.0,0.0,97635.0,70.108246,...,20.620,21.251,14.661810,15.857539,3.148582,3.153462,14.443294,15.660424,3.026261,3.056404
36,ABW,BHS,2010,1,1588.515,0.0,0.0,0.0,101838.0,69.709380,...,23.303,23.417,14.718799,15.883638,3.190024,3.088403,14.661810,15.857539,3.148582,3.153462
37,ABW,BOL,1995,2,3560.684,0.0,1.0,0.0,79805.0,67.362813,...,NaN,0.716,14.093650,15.719879,2.799778,-0.128970,NaN,15.398108,NaN,-0.334075
38,ABW,BOL,1995,2,3560.684,0.0,1.0,0.0,79805.0,67.362813,...,NaN,0.716,14.093650,15.719879,2.799778,-0.128970,NaN,15.398108,NaN,-0.334075
39,ABW,BOL,2000,1,3560.684,0.0,1.0,0.0,90588.0,69.774621,...,16.441,0.879,14.443294,15.943487,3.026261,-0.011061,14.093650,15.719879,2.799778,-0.128970
40,ABW,BOL,2000,1,3560.684,0.0,1.0,0.0,90588.0,69.774621,...,16.441,0.879,14.443294,15.943487,3.026261,-0.011061,14.093650,15.719879,2.799778,-0.128970
41,ABW,BOL,2005,2,3560.684,0.0,1.0,0.0,97635.0,70.108246,...,20.620,0.989,14.661810,16.071968,3.148582,0.020783,14.443294,15.943487,3.026261,-0.011061
42,ABW,BOL,2005,2,3560.684,0.0,1.0,0.0,97635.0,70.108246,...,20.620,0.989,14.661810,16.071968,3.148582,0.020783,14.443294,15.943487,3.026261,-0.011061
43,ABW,BOL,2010,1,3560.684,0.0,1.0,0.0,101838.0,69.709380,...,23.303,1.021,14.718799,16.793569,3.190024,0.660107,14.661810,16.071968,3.148582,0.020783
44,ABW,BOL,2010,1,3560.684,0.0,1.0,0.0,101838.0,69.709380,...,23.303,1.021,14.718799,16.793569,3.190024,0.660107,14.661810,16.071968,3.148582,0.020783
45,ABW,BRA,1990,1,3988.915,0.0,0.0,0.0,62753.0,67.390157,...,NaN,NaN,NaN,19.950971,NaN,1.127200,NaN,NaN,NaN,NaN
46,ABW,BRA,1990,1,3988.915,0.0,0.0,0.0,62753.0,67.390157,...,NaN,NaN,NaN,19.950971,NaN,1.127200,NaN,NaN,NaN,NaN
47,ABW,BRA,1995,1,3988.915,0.0,0.0,0.0,79805.0,67.362813,...,NaN,3.087,14.093650,20.460538,2.799778,1.558145,NaN,19.950971,NaN,1.127200
48,ABW,BRA,1995,1,3988.915,0.0,0.0,0.0,79805.0,67.362813,...,NaN,3.087,14.093650,20.460538,2.799778,1.558145,NaN,19.950971,NaN,1.127200
49,ABW,BRA,2000,1,3988.915,0.0,0.0,0.0,90588.0,69.774621,...,16.441,4.750,14.443294,20.284298,3.026261,1.306710,14.093650,20.460538,2.799778,1.558145

In [23]:
# test gdp vs gdp/capita


formula = """
log_migrantCount ~ log_pop_o + log_pop_d + log_distcap 
+ log_PSR_o + log_PSR_d + log_IMR_o + log_IMR_d 
+ log_urban_o + log_urban_d + log_LA_o + log_LA_d 
+ landlocked_o + landlocked_d 
+ contig + comlang_off + col_dep_ever 
+ t_centered + t_centered_sq + log_gdp_o + log_gdp_d
"""

# 2. Estimation du modèle (On nettoie les NaN avant, sinon ça plante)
# cov_type='HC1' assure des t-stats robustes comme dans votre papier
results1 = smf.ols(formula, data=df_final.dropna()).fit(cov_type='HC1')

# 3. Affichage
print(results1.summary())

formula= """log_migrantCount ~ log_pop_o + log_pop_d + log_distcap 
+ log_PSR_o + log_PSR_d + log_IMR_o + log_IMR_d 
+ log_urban_o + log_urban_d + log_LA_o + log_LA_d 
+ landlocked_o + landlocked_d 
+ contig + comlang_off + col_dep_ever 
+ t_centered + t_centered_sq + log_gdpcap_o + log_gdpcap_d"""
results2 = smf.ols(formula, data=df_final.dropna()).fit(cov_type='HC1')
print(results2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       log_migrantCount   R-squared:                       0.568
Model:                            OLS   Adj. R-squared:                  0.568
Method:                 Least Squares   F-statistic:                     5222.
Date:                Sun, 18 Jan 2026   Prob (F-statistic):               0.00
Time:                        11:54:09   Log-Likelihood:            -1.4741e+05
No. Observations:               69554   AIC:                         2.949e+05
Df Residuals:                   69533   BIC:                         2.950e+05
Df Model:                          20
Covariance Type:                  HC1
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -2.9794      0.208    -14.310      0.000      -3.387      -2.571
log_pop_o         0.2363      0.014     16.756      0.000       0.209       0.264
log_pop_d        -0.0775      0.014     -5.535      0.000      -0.105      -0.050
log_distcap      -1.3047      0.010   -127.166      0.000      -1.325      -1.285
log_PSR_o         0.0292      0.019      1.512      0.130      -0.009       0.067
log_PSR_d        -0.4569      0.022    -21.157      0.000      -0.499      -0.415
log_IMR_o        -0.2788      0.021    -13.254      0.000      -0.320      -0.238
log_IMR_d        -0.0724      0.021     -3.434      0.001      -0.114      -0.031
log_urban_o      -0.4726      0.026    -17.988      0.000      -0.524      -0.421
log_urban_d      -0.3054      0.028    -10.853      0.000      -0.361      -0.250
log_LA_o          0.1315      0.005     24.746      0.000       0.121       0.142
log_LA_d          0.1836      0.005     34.175      0.000       0.173       0.194
landlocked_o     -0.4088      0.022    -18.505      0.000      -0.452      -0.366
landlocked_d     -0.1134      0.021     -5.306      0.000      -0.155      -0.072
contig            1.6809      0.057     29.633      0.000       1.570       1.792
comlang_off       1.6289      0.021     76.036      0.000       1.587       1.671
col_dep_ever      1.6069      0.051     31.295      0.000       1.506       1.708
t_centered       -0.0516      0.002    -23.209      0.000      -0.056      -0.047
t_centered_sq    -0.0036      0.000    -11.359      0.000      -0.004      -0.003
log_gdp_o         0.3648      0.013     27.885      0.000       0.339       0.390
log_gdp_d         0.6073      0.013     46.582      0.000       0.582       0.633
==============================================================================
Omnibus:                      440.859   Durbin-Watson:                   0.609
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              450.022
Skew:                           0.192   Prob(JB):                     1.90e-98
Kurtosis:                       3.085   Cond. No.                     1.73e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.73e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
                            OLS Regression Results
==============================================================================
Dep. Variable:       log_migrantCount   R-squared:                       0.568
Model:                            OLS   Adj. R-squared:                  0.568
Method:                 Least Squares   F-statistic:                     5222.
Date:                Sun, 18 Jan 2026   Prob (F-statistic):               0.00
Time:                        11:54:09   Log-Likelihood:            -1.4740e+05
No. Observations:               69554   AIC:                         2.948e+05
Df Residuals:                   69533   BIC:                         2.950e+05
Df Model:                          20
Covariance Type:                  HC1
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -2.8610      0.208    -13.747      0.000      -3.269      -2.453
log_pop_o         0.5998      0.007     87.218      0.000       0.586       0.613
log_pop_d         0.5280      0.007     77.881      0.000       0.515       0.541
log_distcap      -1.3032      0.010   -127.165      0.000      -1.323      -1.283
log_PSR_o         0.0319      0.019      1.656      0.098      -0.006       0.070
log_PSR_d        -0.4537      0.022    -21.018      0.000      -0.496      -0.411
log_IMR_o        -0.2930      0.021    -14.015      0.000      -0.334      -0.252
log_IMR_d        -0.0866      0.021     -4.140      0.000      -0.128      -0.046
log_urban_o      -0.4743      0.026    -18.043      0.000      -0.526      -0.423
log_urban_d      -0.3199      0.028    -11.341      0.000      -0.375      -0.265
log_LA_o          0.1332      0.005     25.087      0.000       0.123       0.144
log_LA_d          0.1862      0.005     34.666      0.000       0.176       0.197
landlocked_o     -0.4087      0.022    -18.487      0.000      -0.452      -0.365
landlocked_d     -0.1139      0.021     -5.325      0.000      -0.156      -0.072
contig            1.6876      0.057     29.774      0.000       1.576       1.799
comlang_off       1.6298      0.021     76.162      0.000       1.588       1.672
col_dep_ever      1.6029      0.051     31.141      0.000       1.502       1.704
t_centered       -0.0518      0.002    -23.308      0.000      -0.056      -0.047
t_centered_sq    -0.0036      0.000    -11.279      0.000      -0.004      -0.003
log_gdpcap_o      0.3587      0.013     27.501      0.000       0.333       0.384
log_gdpcap_d      0.6058      0.013     46.695      0.000       0.580       0.631
==============================================================================
Omnibus:                      440.837   Durbin-Watson:                   0.610
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              449.976
Skew:                           0.192   Prob(JB):                     1.95e-98
Kurtosis:                       3.085   Cond. No.                     1.63e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.63e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [24]:
# test gdp retardé vs gdp courant


formula = """
log_migrantCount ~ log_pop_o + log_pop_d + log_distcap 
+ log_PSR_o + log_PSR_d + log_IMR_o + log_IMR_d 
+ log_urban_o + log_urban_d + log_LA_o + log_LA_d 
+ landlocked_o + landlocked_d 
+ contig + comlang_off + col_dep_ever 
+ t_centered + t_centered_sq + log_gdpcap_o_lag + log_gdpcap_d_lag
"""

# 2. Estimation du modèle (On nettoie les NaN avant, sinon ça plante)
# cov_type='HC1' assure des t-stats robustes comme dans votre papier
results1 = smf.ols(formula, data=df_final.dropna()).fit(cov_type='HC1')

# 3. Affichage
print(results1.summary())

formula= """log_migrantCount ~ log_pop_o + log_pop_d + log_distcap 
+ log_PSR_o + log_PSR_d + log_IMR_o + log_IMR_d 
+ log_urban_o + log_urban_d + log_LA_o + log_LA_d 
+ landlocked_o + landlocked_d 
+ contig + comlang_off + col_dep_ever 
+ t_centered + t_centered_sq + log_gdpcap_o + log_gdpcap_d"""
results2 = smf.ols(formula, data=df_final.dropna()).fit(cov_type='HC1')
print(results2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       log_migrantCount   R-squared:                       0.569
Model:                            OLS   Adj. R-squared:                  0.569
Method:                 Least Squares   F-statistic:                     5215.
Date:                Sun, 18 Jan 2026   Prob (F-statistic):               0.00
Time:                        11:59:20   Log-Likelihood:            -1.4734e+05
No. Observations:               69554   AIC:                         2.947e+05
Df Residuals:                   69533   BIC:                         2.949e+05
Df Model:                          20
Covariance Type:                  HC1
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           -3.0329      0.209    -14.540      0.000      -3.442      -2.624
log_pop_o            0.6037      0.007     87.594      0.000       0.590       0.617
log_pop_d            0.5340      0.007     78.578      0.000       0.521       0.547
log_distcap         -1.3050      0.010   -127.612      0.000      -1.325      -1.285
log_PSR_o            0.0383      0.019      1.997      0.046       0.001       0.076
log_PSR_d           -0.4388      0.022    -20.327      0.000      -0.481      -0.397
log_IMR_o           -0.3057      0.020    -15.109      0.000      -0.345      -0.266
log_IMR_d           -0.1171      0.020     -5.752      0.000      -0.157      -0.077
log_urban_o         -0.4413      0.026    -17.242      0.000      -0.491      -0.391
log_urban_d         -0.2513      0.028     -9.104      0.000      -0.305      -0.197
log_LA_o             0.1311      0.005     24.607      0.000       0.121       0.142
log_LA_d             0.1828      0.005     33.810      0.000       0.172       0.193
landlocked_o        -0.4047      0.022    -18.313      0.000      -0.448      -0.361
landlocked_d        -0.0992      0.021     -4.627      0.000      -0.141      -0.057
contig               1.6984      0.056     30.145      0.000       1.588       1.809
comlang_off          1.6056      0.021     74.992      0.000       1.564       1.648
col_dep_ever         1.5950      0.051     31.010      0.000       1.494       1.696
t_centered          -0.0376      0.002    -16.631      0.000      -0.042      -0.033
t_centered_sq       -0.0025      0.000     -7.977      0.000      -0.003      -0.002
log_gdpcap_o_lag     0.3443      0.012     28.514      0.000       0.321       0.368
log_gdpcap_d_lag     0.5712      0.012     47.773      0.000       0.548       0.595
==============================================================================
Omnibus:                      457.992   Durbin-Watson:                   0.611
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              467.994
Skew:                           0.196   Prob(JB):                    2.38e-102
Kurtosis:                       3.090   Cond. No.                     1.63e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.63e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
                            OLS Regression Results
==============================================================================
Dep. Variable:       log_migrantCount   R-squared:                       0.568
Model:                            OLS   Adj. R-squared:                  0.568
Method:                 Least Squares   F-statistic:                     5222.
Date:                Sun, 18 Jan 2026   Prob (F-statistic):               0.00
Time:                        11:59:21   Log-Likelihood:            -1.4740e+05
No. Observations:               69554   AIC:                         2.948e+05
Df Residuals:                   69533   BIC:                         2.950e+05
Df Model:                          20
Covariance Type:                  HC1
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -2.8610      0.208    -13.747      0.000      -3.269      -2.453
log_pop_o         0.5998      0.007     87.218      0.000       0.586       0.613
log_pop_d         0.5280      0.007     77.881      0.000       0.515       0.541
log_distcap      -1.3032      0.010   -127.165      0.000      -1.323      -1.283
log_PSR_o         0.0319      0.019      1.656      0.098      -0.006       0.070
log_PSR_d        -0.4537      0.022    -21.018      0.000      -0.496      -0.411
log_IMR_o        -0.2930      0.021    -14.015      0.000      -0.334      -0.252
log_IMR_d        -0.0866      0.021     -4.140      0.000      -0.128      -0.046
log_urban_o      -0.4743      0.026    -18.043      0.000      -0.526      -0.423
log_urban_d      -0.3199      0.028    -11.341      0.000      -0.375      -0.265
log_LA_o          0.1332      0.005     25.087      0.000       0.123       0.144
log_LA_d          0.1862      0.005     34.666      0.000       0.176       0.197
landlocked_o     -0.4087      0.022    -18.487      0.000      -0.452      -0.365
landlocked_d     -0.1139      0.021     -5.325      0.000      -0.156      -0.072
contig            1.6876      0.057     29.774      0.000       1.576       1.799
comlang_off       1.6298      0.021     76.162      0.000       1.588       1.672
col_dep_ever      1.6029      0.051     31.141      0.000       1.502       1.704
t_centered       -0.0518      0.002    -23.308      0.000      -0.056      -0.047
t_centered_sq    -0.0036      0.000    -11.279      0.000      -0.004      -0.003
log_gdpcap_o      0.3587      0.013     27.501      0.000       0.333       0.384
log_gdpcap_d      0.6058      0.013     46.695      0.000       0.580       0.631
==============================================================================
Omnibus:                      440.837   Durbin-Watson:                   0.610
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              449.976
Skew:                           0.192   Prob(JB):                     1.95e-98
Kurtosis:                       3.085   Cond. No.                     1.63e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.63e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [31]:
import numpy as np
import statsmodels.formula.api as smf
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

# 1. Liste EXHAUSTIVE des variables du modèle
# C'est crucial : si une seule manque, la ligne doit sauter
all_features = [
    'log_migrantCount', 
    'log_pop_o', 'log_pop_d', 'log_distcap', 
    'log_PSR_o', 'log_PSR_d', 'log_IMR_o', 'log_IMR_d', 
    'log_urban_o', 'log_urban_d', 'log_LA_o', 'log_LA_d', 
    'landlocked_o', 'landlocked_d', 
    'contig', 'comlang_off', 'col_dep_ever', 
    't_centered', 't_centered_sq'
]

# 2. Nettoyage STRICT
# On ne garde que les lignes où TOUTES ces variables sont présentes
df_clean = df_final.dropna(subset=all_features).copy()

# 3. Split Train/Test (Test = 2010)
train_df = df_clean[df_clean['year'] < 2010]
test_df  = df_clean[df_clean['year'] == 2010]

print(f"Lignes d'entraînement : {len(train_df)}")
print(f"Lignes de test (2010): {len(test_df)}")

# 4. Entraînement
formula = """
log_migrantCount ~ log_pop_o + log_pop_d + log_distcap 
+ log_PSR_o + log_PSR_d + log_IMR_o + log_IMR_d 
+ log_urban_o + log_urban_d + log_LA_o + log_LA_d 
+ landlocked_o + landlocked_d 
+ contig + comlang_off + col_dep_ever 
+ t_centered + t_centered_sq 

"""

if not test_df.empty:
    model = smf.ols(formula, data=train_df).fit()

    # 5. Prédiction & Métriques
    pred_log = model.predict(test_df)
    
    y_pred_real = np.exp(pred_log)
    y_true_real = np.exp(test_df['log_migrantCount'])

    mse = mean_squared_error(y_true_real, y_pred_real)
    mape = mean_absolute_percentage_error(y_true_real, y_pred_real)

    print(f"\n--- PERFORMANCE OLS (Baseline 2010) ---")
    print(f"MSE  : {mse:,.0f}")
    print(f"MAPE : {mape:.2%}")
else:
    print("ERREUR : Plus aucune donnée pour 2010 après nettoyage complet.")

Lignes d'entraînement : 82963
Lignes de test (2010): 20750

--- PERFORMANCE OLS (Baseline 2010) ---
MSE  : 4,178,612,349
MAPE : 1463.77%

MSE ? MAPE ? comparaison avec ajout gdpcap et sans. 

Random forest: